[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' https://cdn.jsdelivr.net https://utsohlqsnojqlouzmouu.supabase.co; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; connect-src 'self' https://utsohlqsnojqlouzmouu.supabase.co;"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"